---
- name: cron job
  hosts: ec2

  tasks:
  - name: create a file
    file: 
      path: /home/ubuntu/test.sh
      state: touch
    
  - name: add content on my file
    shell: echo "Hello World" >> /home/ubuntu/test.sh

  - name: create a cron job
    cron:
      name: test
      minute: 1
      hour: "*"
      day: "*"
      month: "*"
      weekday: "*"
      user:  ubuntu
      job: /home/ubuntu/test.sh
    register: result

  - debug:
      var: result

  - name: remove cron job
    cron:
      name: VAR
      env: yes
      user: ubuntu
      job: /home/ubuntu/test.shcdsdsd
      insertafter: 
    register: delete_result


  - debug:
      var: delete_result


