# ---
# - name: create a user and group 
#   hosts: ec2
#   become: yes

#   tasks:

#   - name: create a user
#     user:
#       name: "{{ item }}"
#       comment: new user yash
#       state: present    # absent to delete user 
#       home: /home/{{ item }}
#       shell: /bin/bash
#       password: "{{ '{{ item }}' | password_hash('sha512') }}"
#     loop:
#       - raju
#       - yash
#       - kumar
#     register:
#       result

#   - debug:
#       var: result


---
- name: create a user and group 
  hosts: ec2
  become: yes
  vars:
    - apps: [raju, yash, kumar]
  tasks:
  - name: create a user
    user:
      name: "{{ item }}"
      comment: new user 
      state: present    # absent to delete user 
      home: /home/{{ item }}
      shell: /bin/bash
      password: "{{ '{{ item }}' | password_hash('sha512') }}"
    with_items: "{{ apps }}"
    register:
      result

  - debug:
      var: result


 

