---
- name: create a user and group 
  hosts: ec2
  become: yes

  tasks:
  - name: create group QA
    group:
      name: QA
      state: present

  - name: create a user
    user:
      name: yash
      comment: new user yash
      state: present    # absent to delete user 
      home: /home/yash
      shell: /bin/bash
      group: QA
      password: "{{ 'yash' | password_hash('sha512') }}"
    register:
      result

  - debug:
      var: result


 

